# Basic Site Settings
locale                   : "en-US"
title                    : "Yeo Dong Youn"
title_separator          : "-"
name                     : &name "Yeo Dong Youn"
description              : &description "Personal Website of Yeo Dong Youn"
url                      : https://YeoDongYoun1995.github.io
baseurl                  : ""
repository               : "YeoDongYoun1995/YeoDongYoun1995.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Yeo Dong Youn"
  bio              : "Ph.D. student at SNU Graduate School of Data Science"
  location         : "Seoul, South Korea"
  employer         : "Causality Lab, SNU"
  email            : "dbsduehd95@snu.ac.kr"
  googlescholar    : "https://scholar.google.com/citations?user=yKehWT4AAAAJ&hl"
  github           : "YeodongYoun1995"

# Navigation Tabs
header_pages:
  - publications.md
  - cv.md
  - contact.md

# Collections
collections:
  teaching:
    output: false
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: false
  talks:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: cv
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: contact
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: archive
      author_profile: true

# Other Configurations (unchanged)
teaser                   :  
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : 
atom_feed:
  hide                   : false
  path                   :

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
